### ISSUE TITLE
Button doesn't appear when viewing video from playlist

### ISSUE THREAD

**Issue by ClawhammerLobotomy** [gurumukhi/youtube-screenshot#10]
When starting a video from a playlist, the screenshot button does not appear.

The code is triggered first on the playlist page, but does not get re-triggered when the player appears.
I believe this is likely due to how Youtube doesn't load a new page in the typical way when going from playlist to video and to other videos.
If refreshing the page after the video is selected, the button will then appear like normal.

Steps to reproduce:
1. Open a playlist with any videos present (Watch later for example)
2. Click on any of the videos inside
3. No screenshot button appears on the player
4. Refresh page
5. Screenshot button appears

Additionally, the button will never appear when navigating to other videos once you start from a playlist.

**Comment by kiwi5** [comment]
Alternative workaround instead of reloading the page is to disable & re-enable the addon itself on the addon list.

It is maybe a bit more annoying to do, but there are cases where you don't want to reload the page, like if you started writing a comment or have some comments loaded and don't want to reload & check which ones you already read or not.

**Comment by joggee-fr** [comment]
@ClawhammerLobotomy, could you test again with up-to-date version? I think PR #20 could have fixed this issue.

**Comment by ClawhammerLobotomy** [comment]
Seems like this is working now. Nice job.
